version: "3"
services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8080
    volumes:
      - .:/code
      - /var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    ports: 
      - "8080:8080"
    
